language: ruby

services:
  - docker

## reference on file encryption in travis: https://docs.travis-ci.com/user/encrypting-files/
before_install:
  - docker pull amazoncorretto:11
  - docker pull google/cloud-sdk:alpine
  - openssl aes-256-cbc -K $encrypted_bd9783f2cc1e_key -iv $encrypted_bd9783f2cc1e_iv -in gothic-dreamer-271402-bfe27e1015cc.json.enc -out gothic-dreamer-271402-bfe27e1015cc.json -d


script:
  - docker run --rm -v $TRAVIS_BUILD_DIR:/source -v artifact_volume:/artifact_volume amazoncorretto:11 /bin/sh -c "cd /source ; ./gradlew clean build -x test"


after_script:
  - docker build -t joelin/gh-service:latest --build-arg JAR_FILE=build/libs/gh-service-1.0.0.jar --build-arg SERVICE_ACCOUNT_JSON=gothic-dreamer-271402-bfe27e1015cc.json .
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push joelin/gh-service:latest
  #- docker run --rm -v $TRAVIS_BUILD_DIR:/source google/cloud-sdk:284.0.0-alpine /bin/sh -c "cd /source ; sh deploy_gcp.sh"
