version: '3'
services:
  gh-service-api:
    image: io.geekhub/gh-service
    depends_on:
      - database
    ports:
     - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  database:
    image: "postgres:alpine"
    environment:
      - POSTGRES_PASSWORD=%90nw3Uhw
      - POSTGRES_DB=gh-service
    ports:
      - "5432:5432"
