# https://kubernetes.io/docs/concepts/services-networking/ingress/#default-backend
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gh-ingress
spec:
  tls:
    - secretName: gh-secret-tls2
  defaultBackend:
    service:
      name: gh-service-nodeport
      port:
        number: 80
